version: '3.3'

services:
 database:
    image: mysql:8.0.21
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "operantic"
      MYSQL_DATABASE: "operanticdb"
      MYSQL_USER: "operantic"
      MYSQL_PASSWORD: "operantic"
    ports:
      - 3307:3306
     
 springapi:
    image: openjdk:8-jdk-alpine
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: springapi
    ports:
      - 8081:8080
    depends_on:
      - database
    networks:
      - backendNetwork
 
 rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management'
    ports:
      - "5672:5672"
      - "15672:15672"
  
networks:
  backendNetwork:
  
  
